### ISSUE TITLE
"label_l" and "label_r" parameters are weird, let's replace it with one "logo" image

### ISSUE THREAD

**Issue by vas3k** [nDmitry/ogimgd#3]
Since we need to load the club icon anyway, how about replacing the entire logo in the bottom right corner with a picture? I think it would be easier for us instead of using the cryptic "label_l" and "r" params. We can limit their width or height and resize the logo image based on that.

**Comment by nDmitry** [comment]
With label parts you can either make the icon be left or right from the text (by omitting `label_l` or `label_r`), or between.
Or you can omit the labels entirely and use the icon only. Though the icon must be a square for now because the size options aren't exported.

It could also be done either by:
1. Using one logo picture with text or whatever on it. Than its width should be `auto` and height is specified in the `preview.Options`.
2. Exporting icon size options in the URL and use them together with `icon` param alone since label params are already optional.

Option 2 looks even more complicated to me. Option 1 is simple and even more customizable, so I would go with it!
